/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/complete-first-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeFirstLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCommunities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlatformUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listevents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/donors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listdonors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/donations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listdonations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listexpenses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listinvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listreports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listuploads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listsync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listaudit-logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities/{communityId}/error-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        get: operations["listerror-logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        CompleteFirstLogin: {
            challengeToken: string;
            newPassword: string;
        };
        MemberCreate: {
            /** @constant */
            kind: "new";
            /** Format: email */
            email: string;
            fullName: string;
            temporaryPassword: string;
            /** @enum {unknown} */
            role: "admin" | "collector" | "viewer";
        } | {
            /** @constant */
            kind: "existing";
            /** Format: email */
            email: string;
            /** @enum {unknown} */
            role: "admin" | "collector" | "viewer";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Session or password-change challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeFirstLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteFirstLogin"];
            };
        };
        responses: {
            /** @description Session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Non-enumerating recovery response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Password reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token family revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user and memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCommunities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accessible communities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Community members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Account and membership created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPlatformUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Super-admin account list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listevents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listdonors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listdonations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listexpenses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listinvoices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listreports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listuploads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listsync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "listaudit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "listerror-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
